import Head from 'next/head'
import { Inter } from 'next/font/google'
import RegistrationForm from '@/components/RegistrationForm'

export default function Home() {
  return (
    <>
      <Head>
        <title>Class 16</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>React Hook Form</h1>
        <RegistrationForm />
      </main>
    </>
  )
}
